apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: assisted-events-stream-g5x2
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: assisted-events-stream-g5x2
    app.kubernetes.io/part-of: assisted-events-stream
  name: assisted-events-stream-g5x2
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: assisted-events-stream-g5x2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: assisted-events-stream-g5x2
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-migration-tenant/assisted-events-stream/assisted-events-stream-g5x2@sha256:f91c4f80ebb160d3039adf2732a99e1a6afa09e929aa69bafd907bcb7f7cf041
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 6379
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
