apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: assisted-events-stream-g5x2
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: assisted-events-stream-g5x2
    app.kubernetes.io/part-of: assisted-events-stream
  name: assisted-events-stream-g5x2
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app.kubernetes.io/instance: assisted-events-stream-g5x2
status:
  loadBalancer: {}
